version: '2'
services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    volumes:
      - ./src:/usr/src/app/src
      - ./coverage:/usr/src/app/coverage
    command: "npm test"
