version: '2'
services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    volumes:
      - ./src:/usr/src/app/src
      - ./coverage:/usr/src/app/coverage
    command: "node_modules/.bin/babel-node node_modules/.bin/isparta cover --report html node_modules/.bin/_mocha -- --recursive src/test"
