version: '2'
services:
  web:
    network_mode: host
    extends:
      file: docker-compose.yml
      service: web
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app/src
    command: "node bin/debug.js --no-preload --web-host 0.0.0.0 ./src/app.js"
